### ISSUE TITLE
Release 1.6.0 unbundle_nbi subprocess.Popen environment missing

### ISSUE THREAD

**Issue by SkyLeach** [eliben/pyelftools#185]
Insufficient testing.  Apparently the user environment is not being passed to subprocess.Popen (copied from `bintools/unbundleNX9K.py`) which makes the shebang in disNBI fail to find perl:

```
INFO:imgunbundler.unbundlers.unbundle_nbi:Extracting files from /data/magregor-specialtest/nxos.7.0.3.IHD8.0.397.bin to /data/output/magregor ...
ERROR:imgunbundler.unbundlers.unbundle_nbi:DISNBI return code 127:
/usr/bin/env: ‘perl -w’: No such file or directory


Traceback (most recent call last):
  File "/home/magregor/src/imgunbundle/imgunbundler/unbundlers/unbundle_nbi.py", line 86, in unbundle
    raise ImgunbundleInternalError(errmsg)
ImgunbundleInternalError: DISNBI return code 127:
/usr/bin/env: ‘perl -w’: No such file or directory


ERROR:imgunbundler.unbundlers.unbundle_generic:Problem with <imgunbundler.unbundlers.unbundle_nbi.unbundle_nbi object at 0x7fe66b478610>
Traceback (most recent call last):
  File "/home/magregor/src/imgunbundle/imgunbundler/unbundlers/unbundle_generic.py", line 210, in unbundle_worker
    result = unbundler_instance.unbundle(fileobj)
  File "/home/magregor/src/imgunbundle/imgunbundler/unbundlers/unbundle_nbi.py", line 92, in unbundle
    raise ImgunbundleInternalError(e.message)
ImgunbundleInternalError: DISNBI return code 127:
/usr/bin/env: ‘perl -w’: No such file or directory


DISNBI return code 127:
/usr/bin/env: ‘perl -w’: No such file or directory


Traceback (most recent call last):
  File "/home/magregor/.virtualenvs/imgunbundler/bin/imgunbundle", line 11, in <module>
    load_entry_point('imgunbundler', 'console_scripts', 'imgunbundle')()
  File "/home/magregor/src/imgunbundle/imgunbundler/imgunbundle.py", line 290, in main
    run(imgfile, outdir)
  File "/home/magregor/src/imgunbundle/imgunbundler/imgunbundle.py", line 90, in run
    first_unbundler.unbundle_generic(fileobj, 0, **kwargs)
  File "/home/magregor/src/imgunbundle/imgunbundler/unbundlers/unbundle_generic.py", line 327, in unbundle_generic
    is_bundle = self.unbundle_worker(fileobj, **kwargs)
  File "/home/magregor/src/imgunbundle/imgunbundler/unbundlers/unbundle_generic.py", line 218, in unbundle_worker
    raise errorcodes.ImgunbundleInternalError(str(e))
imgunbundler.errorcodes.ImgunbundleInternalError: DISNBI return code 127:
/usr/bin/env: ‘perl -w’: No such file or directory
```

**Comment by SkyLeach** [comment]
so so sorry, I'm on public github instead of private.  🥇
