### ISSUE TITLE
readelf.py --debug-dump=decodedline fails

### ISSUE THREAD

**Issue by smani** [eliben/pyelftools#23]
Running `python scripts/readelf.py --debug-dump=decodedline test/testfiles_for_unittests/arm_with_form_indirect.elf` fails with the following error:

```
Traceback (most recent call last):
  File "scripts/readelf.py", line 1136, in <module>
    main()
  File "scripts/readelf.py", line 1115, in main
    readelf.display_debug_dump(options.debug_dump_what)
  File "scripts/readelf.py", line 635, in display_debug_dump
    self._dump_debug_line_programs()
  File "scripts/readelf.py", line 872, in _dump_debug_line_programs
    cu_filename = bytes2str(lineprogram['file_entry'][0].name)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sevaa** [comment]
@smani @eliben This was fixed.
