### ISSUE TITLE
off-by-one parsing eh_frame

### ISSUE THREAD

**Issue by rhelmot** [eliben/pyelftools#288]
When enumerating `elffile.get_dwarf_info().EH_CFI_entries()` for 
[this file](https://github.com/eliben/pyelftools/files/4207796/in.acng.gz), the following error occurs:

```
apt-cacher-ng_2-2_mips64el.deb.data/usr/lib/apt-cacher-ng/in.acng
Traceback (most recent call last):
  File "/home/audrey/angr/pyelftools/elftools/construct/core.py", line 351, in _parse
    return self.packer.unpack(_read_stream(stream, self.length))[0]
  File "/home/audrey/angr/pyelftools/elftools/construct/core.py", line 293, in _read_stream
    raise FieldError("expected %d, found %d" % (length, len(data)))
elftools.construct.core.FieldError: expected 4, found 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/audrey/angr/pyelftools/elftools/common/utils.py", line 40, in struct_parse
    return struct.parse_stream(stream)
  File "/home/audrey/angr/pyelftools/elftools/construct/core.py", line 190, in parse_stream
    return self._parse(stream, Container())
  File "/home/audrey/angr/pyelftools/elftools/construct/core.py", line 353, in _parse
    raise FieldError(ex)
elftools.construct.core.FieldError: expected 4, found 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./try_load.py", line 14, in <module>
    angr.Project(filename, auto_load_libs=False)
  File "/home/audrey/angr/angr/angr/project.py", line 129, in __init__
    self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
  File "/home/audrey/angr/cle/cle/loader.py", line 134, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *preload_libs, *force_load_libs, preloading=(main_binary, *preload_libs))
  File "/home/audrey/angr/cle/cle/loader.py", line 655, in _internal_load
    obj = self._load_object_isolated(main_spec)
  File "/home/audrey/angr/cle/cle/loader.py", line 813, in _load_object_isolated
    return backend_cls(full_spec, is_main_bin=self.main_object is None, loader=self, **options)
  File "/home/audrey/angr/cle/cle/backends/elf/elf.py", line 146, in __init__
    self._load_function_hints_from_fde(dwarf)
  File "/home/audrey/angr/cle/cle/backends/elf/elf.py", line 446, in _load_function_hints_from_fde
    for entry in dwarf.EH_CFI_entries():
  File "/home/audrey/angr/pyelftools/elftools/dwarf/dwarfinfo.py", line 191, in EH_CFI_entries
    return cfi.get_entries()
  File "/home/audrey/angr/pyelftools/elftools/dwarf/callframe.py", line 71, in get_entries
    self.entries = self._parse_entries()
  File "/home/audrey/angr/pyelftools/elftools/dwarf/callframe.py", line 80, in _parse_entries
    entries.append(self._parse_entry_at(offset))
  File "/home/audrey/angr/pyelftools/elftools/dwarf/callframe.py", line 93, in _parse_entry_at
    self.base_structs.Dwarf_uint32(''), self.stream, offset)
  File "/home/audrey/angr/pyelftools/elftools/common/utils.py", line 42, in struct_parse
    raise ELFParseError(str(e))
elftools.common.exceptions.ELFParseError: expected 4, found 3
```

when I try to go in and debug the issue, I find that at the time of the crash, the stream points to offset 0x1e1 in the section, and `readelf --debug-dump=frames` shows:

```
<...snip>

00000188 0000000000000054 00000024 FDE cie=00000168 pc=0000000000001100..0000000000001848
  Augmentation data:     08 00 02 00 00 00 00 00
  DW_CFA_advance_loc: 4 to 0000000000001104
  DW_CFA_def_cfa_offset: 1984
  DW_CFA_advance_loc: 4 to 0000000000001108
  DW_CFA_offset: r28 at cfa-24
  DW_CFA_advance_loc: 16 to 0000000000001118
  DW_CFA_offset: r16 at cfa-88
  DW_CFA_advance_loc: 20 to 000000000000112c
  DW_CFA_offset: r18 at cfa-72
  DW_CFA_offset: r17 at cfa-80
  DW_CFA_advance_loc: 44 to 0000000000001158
  DW_CFA_offset: r31 at cfa-8
  DW_CFA_offset: r20 at cfa-56
  DW_CFA_offset: r19 at cfa-64
  DW_CFA_offset: r30 at cfa-16
  DW_CFA_offset: r23 at cfa-32
  DW_CFA_offset: r22 at cfa-40
  DW_CFA_offset: r21 at cfa-48
  DW_CFA_advance_loc2: 264 to 0000000000001260
  DW_CFA_remember_state
  DW_CFA_def_cfa_offset: 0
  DW_CFA_restore: r16
  DW_CFA_restore: r17
  DW_CFA_restore: r18
  DW_CFA_restore: r19
  DW_CFA_restore: r20
  DW_CFA_restore: r21
  DW_CFA_restore: r22
  DW_CFA_restore: r23
  DW_CFA_restore: r28
  DW_CFA_restore: r30
  DW_CFA_restore: r31
  DW_CFA_restore_state
  DW_CFA_nop
  DW_CFA_nop
  DW_CFA_nop
  DW_CFA_nop
  DW_CFA_nop
  DW_CFA_nop
  DW_CFA_nop

000001e0 ZERO terminator
```

So the parser got off-by-one at some point and now can't read the EOF marker. I verified that it correctly starts parsing an entity at 0x188, and reads an even amount for the augmentation data length, but after reading the augmentation data length the stream is seeked to an odd offset, such that the odd offset + the read length == 0x1e0. I suspect that this is because `CallFrameInfo._read_augmentation_data`'s use of a uleb128 to unpack the length is incorrect, but I have so little insight into how this stuff is supposed to work that I can't think of where to check that.

I can tell that when `end_offset` is computed in `_parse_entry_at`, that value _is_ correct, 0x1e0. Should there be an assertion there that it's equal to `self.stream.tell()`?

**Comment by eliben** [comment]
@pmderodat

**Comment by pmderodat** [comment]
Hello! Thank you @rhelmot for reporting this and providing the reproducer. I think I understood the problem, and have a candidate patch to fix this. I still need to do a bit of work in order to submit a proper testcase with it. I’ll keep you updated.
