### ISSUE TITLE
2 unit test failures with python 3.11.0a1 due to using removed unittest aliases

### ISSUE THREAD

**Issue by rathann** [eliben/pyelftools#377]
```
$ python3 -V
Python 3.11.0a1
$ cd pyelftools-0.27
$ /usr/bin/python3 test/run_all_unittests.py
E................E.................................................................
======================================================================
ERROR: test_reloc (test_arm_call_reloc.TestARMRElocation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pyelftools-0.27/test/test_arm_call_reloc.py", line 41, in test_reloc
    self.assertEquals(do_relocation(rel_elf),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TestARMRElocation' object has no attribute 'assertEquals'

======================================================================
ERROR: test_die_size (test_die_size.TestDieSize)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pyelftools-0.27/test/test_die_size.py", line 29, in test_die_size
    self.assertEquals(child.size, 3)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TestDieSize' object has no attribute 'assertEquals'

----------------------------------------------------------------------
Ran 83 tests in 2.752s

FAILED (errors=2)
```

See:

https://bugs.python.org/issue45162
https://docs.python.org/3.11/whatsnew/3.11.html#removed

Simple fix:
```diff
diff -up pyelftools-0.27/test/test_arm_call_reloc.py.py311 pyelftools-0.27/test/test_arm_call_reloc.py
--- pyelftools-0.27/test/test_arm_call_reloc.py.py311	2020-10-27 14:42:31.000000000 +0100
+++ pyelftools-0.27/test/test_arm_call_reloc.py	2021-11-02 15:12:12.843113102 +0100
@@ -38,7 +38,7 @@ class TestARMRElocation(unittest.TestCas
             elf = ELFFile(f)
 
             # Comparison of '.text' section data
-            self.assertEquals(do_relocation(rel_elf),
+            self.assertEqual(do_relocation(rel_elf),
                               elf.get_section_by_name('.text').data())
 
 if __name__ == '__main__':
diff -up pyelftools-0.27/test/test_die_size.py.py311 pyelftools-0.27/test/test_die_size.py
--- pyelftools-0.27/test/test_die_size.py.py311	2020-10-27 14:42:31.000000000 +0100
+++ pyelftools-0.27/test/test_die_size.py	2021-11-02 15:12:27.929234127 +0100
@@ -26,7 +26,7 @@ class TestDieSize(unittest.TestCase):
             dwarfinfo = elffile.get_dwarf_info()
             for CU in dwarfinfo.iter_CUs():
                  for child in CU.get_top_DIE().iter_children():
-                     self.assertEquals(child.size, 3)
+                     self.assertEqual(child.size, 3)
 
 if __name__ == '__main__':
     unittest.main()
```

**Comment by eliben** [comment]
Please see #374
