### ISSUE TITLE
UnboundLocalError: local variable 'stringtable' referenced before assignment

### ISSUE THREAD

**Issue by pgebhard** [eliben/pyelftools#49]
I tried running the following command: python readelf.py meander.debug -e

and I received the Traceback shown below:

Traceback (most recent call last):
  File "../../lib/pyelftools-0.22/scripts/readelf.py", line 1136, in <module>
    main()
  File "../../lib/pyelftools-0.22/scripts/readelf.py", line 1101, in main
    show_heading=not do_file_header)
  File "../../lib/pyelftools-0.22/scripts/readelf.py", line 170, in display_program_headers
    for segment in self.elffile.iter_segments():
  File "/usr/local/lib/python2.7/site-packages/elftools/elf/elffile.py", line 109, in iter_segments
    yield self.get_segment(i)
  File "/usr/local/lib/python2.7/site-packages/elftools/elf/elffile.py", line 103, in get_segment
    return self._make_segment(segment_header)
  File "/usr/local/lib/python2.7/site-packages/elftools/elf/elffile.py", line 222, in _make_segment
    return DynamicSegment(segment_header, self.stream, self)
  File "/usr/local/lib/python2.7/site-packages/elftools/elf/dynamic.py", line 123, in __init__
    Dynamic.__init__(self, stream, elffile, stringtable, self['p_offset'])
UnboundLocalError: local variable 'stringtable' referenced before assignment

**Comment by eliben** [comment]
Closing due to inactivity. Please reopen or open a new one if you're hitting the same issue.
