### ISSUE TITLE
describe_DWARF_expr() raises on some inputs.

### ISSUE THREAD

**Issue by scudette** [eliben/pyelftools#61]
```
$ python scripts/readelf.py --debug-dump=info /tmp/module_dwarf.ko 
....
 <2><359>: Abbrev Number: 13 (DW_TAG_member)
    <35a>   DW_AT_name        : (indirect string, offset: 0xab00): counter  
    <35e>   DW_AT_decl_file   : 5   
    <35f>   DW_AT_decl_line   : 176 
    <360>   DW_AT_type        : <0x70>  
Traceback (most recent call last):
  File "scripts/readelf.py", line 1170, in <module>
    main()
  File "scripts/readelf.py", line 1149, in main
    readelf.display_debug_dump(options.debug_dump_what)
  File "scripts/readelf.py", line 658, in display_debug_dump
    self._dump_debug_info()
  File "scripts/readelf.py", line 881, in _dump_debug_info
    attr, die, section_offset)))
  File "./elftools/dwarf/descriptions.py", line 38, in describe_attr_value
    extra_info = extra_info_func(attr, die, section_offset)
  File "./elftools/dwarf/descriptions.py", line 388, in _location_list_extra
    return describe_DWARF_expr(attr.value, die.cu.structs)
  File "./elftools/dwarf/descriptions.py", line 149, in describe_DWARF_expr
    dwarf_expr_dumper.process_expr(expr)
  File "./elftools/dwarf/dwarf_expr.py", line 119, in process_expr
    self.stream = BytesIO(bytelist2string(expr))
  File "./elftools/common/utils.py", line 19, in bytelist2string
    return b''.join(int2byte(b) for b in bytelist)
TypeError: 'int' object is not iterable
```

The sample file is at:
https://drive.google.com/file/d/0B9hc84IflFGbSDJ5NnNQRFotZDA/view?usp=sharing

**Comment by eliben** [comment]
Thanks for the report

**Comment by riyadparvez** [comment]
+1. I'm also having same issue.

**Comment by sethml** [comment]
Possibly fixed by pull request #89.

**Comment by eliben** [comment]
Can you please verify if this was fixed?

**Comment by eliben** [comment]
Tried running readelf.py on the originally reported file, no errors.
