### ISSUE TITLE
UnicodeDecodeError with python 3.4.3 on OS X

### ISSUE THREAD

**Issue by liudangyi** [eliben/pyelftools#77]
```
$ python
Python 3.4.3 (default, Feb 25 2015, 21:28:45) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from elftools.elf.elffile import ELFFile
>>> e = ELFFile(open("some_elf_file"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/elftools/elf/elffile.py", line 50, in __init__
    self._identify_file()
  File "/usr/local/lib/python3.4/site-packages/elftools/elf/elffile.py", line 200, in _identify_file
    magic = self.stream.read(4)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 32-33: invalid continuation byte
```
There's no such an error with python 2.7.10.

**Comment by eliben** [comment]
Can you please check if this happens only with `master` branch or with the latest release of pyelftools as well? Does this happen for a particular ELF file, or all? Do the tests of pyelftools run successfully on your machine?

**Comment by liudangyi** [comment]
It's my fault. I forgot to open the file with the 'b' flag. When I change the code to `ELFFile(open("some_elf_file"))`, everything performs well.

**Comment by liudangyi** [comment]
However, in 2.7.10 I do not need to specify the binary mode.

**Comment by eliben** [comment]
Since ELF files are binary, it's always important to specify binary mode when opening them. This is reflected in all the pyelftools usage examples.
